# Generated by Django 5.2.3 on 2025-07-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_full_name_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('head_manager', 'Head Manager'), ('store_manager', 'Store Manager'), ('cashier', 'Cashier')], max_length=20),
        ),
    ]
