# Generated by Django 5.2.3 on 2025-07-05 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_alter_product_category_delete_category'),
        ('transactions', '0004_transaction_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_orders', to='Inventory.product'),
        ),
    ]
