# Generated by Django 5.2.3 on 2025-07-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='customer_name',
            field=models.CharField(blank=True, default='Walk-in Customer', max_length=100),
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
